### ISSUE TITLE
TypeError: expected string or buffer

### ISSUE THREAD

**Issue by liu697** [AutoSurveys/AutoSurvey#25]
Traceback (most recent call last):
  File "main.py", line 88, in <module>
    main(args)
  File "main.py", line 72, in main
    outline_with_description, outline_wo_description = write_outline(args.topic, args.model, args.section_num, args.outline_reference_num, db, args.api_key, args.api_url)
  File "main.py", line 33, in write_outline
    outline = outline_writer.draft_outline(topic, outline_reference_num, 30000, section_num)
  File "/data/user20300129/AutoSurvey/src/agents/outline_writer.py", line 34, in draft_outline
    outlines = self.generate_rough_outlines(topic=topic, papers_chunks = abs_chunks, titles_chunks = titles_chunks, section_num=section_num)
  File "/data/user20300129/AutoSurvey/src/agents/outline_writer.py", line 113, in generate_rough_outlines
    self.output_token_usage += self.token_counter.num_tokens_from_list_string(outlines)
  File "/data/user20300129/AutoSurvey/src/utils.py", line 24, in num_tokens_from_list_string
    num += len(self.encoding.encode(s))
  File "/data/user20300129/.conda/envs/AutoSurvey/lib/python3.8/site-packages/tiktoken/core.py", line 116, in encode
    if match := _special_token_regex(disallowed_special).search(text):
TypeError: expected string or buffer
Has anyone encountered this situation before? How can it be resolved?

**Comment by GuoQi2000** [comment]
This situation occurs when the API call returns None. You can refer to issue #5  for possible solutions.
